#pragma once
#include <stdlib.h>
#include <stdbool.h>
// parse the extracted tokens
void parse();
bool defVar();
bool defFunc();
bool block();
bool baseType();
bool funcParams();
bool funcParam();
bool instr();
bool expr();
bool exprLogic();
bool exprAssign();
bool exprComp();
bool exprAdd();
bool exprMul();
bool exprPrefix();
bool factor();
void help();